project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Formation R"

  page-footer:
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    
  sidebar:
    pinned: true
    align: center
    style: "docked"
    #search: true
    #collapse-level: 1
    contents:
      - href: index.qmd
        text: Introduction
      - href: slides.qmd
        text: Slides
      - href: exercice_1.qmd
        text: Exercice 1
      - href: exercice_2.qmd
        text: Exercice 2
      - href: exercice_3.qmd
        text: Exercice_3
      - href: exercice_4.qmd
        text: Exercice 4
      - href: ressources.qmd
        text: Ressources
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true